CREATE TABLE Kinect_Games
(
	id INT NOT NULL AUTO_INCREMENT,
	Name VARCHAR(30) NOT NULL,
	UNIQUE(Name),
	PRIMARY KEY (id)
);

CREATE TABLE Kinect_Scores
(
	id INT NOT NULL AUTO_INCREMENT,
	GameID INT NOT NULL,
	Name VARCHAR(50) NOT NULL,
	Value INT NOT NULL,
	PRIMARY KEY (id),
	FOREIGN KEY (GameID) REFERENCES Kinect_Games(id)
);


